import { single, slugify } from './helpers';
import type { SeedProduct, SeedSpecs } from './types';

const CAT = 'jogos-de-tabuleiro';

type Game = {
  name: string;
  brand: string;
  /** Preço de varejo online no Brasil (centavos), coletado em set/2026. */
  cents: number;
  /** Número inventado de referência (9xxx): não existe na Tray. */
  ref: number;
  desc: string;
  specs?: SeedSpecs;
  cols?: string[];
  weight?: number;
  slug?: string;
  status?: SeedProduct['status'];
};

function game(input: Game): SeedProduct {
  return single({
    slug: input.slug ?? slugify(input.name),
    name: input.name,
    brand: input.brand,
    category: CAT,
    code: `JTB-${input.ref}`,
    price_cents: input.cents,
    description: input.desc,
    collections: input.cols,
    specs: input.specs,
    weight_g: input.weight,
    status: input.status,
  });
}

// Jogos populares no Brasil (editoras Devir, Galápagos, Grok Games e MeepleBR). Sem imagem: o
// catálogo real da Geek Store ainda não tem estes títulos.
export const marketBoardGames: SeedProduct[] = [
  // ── Devir ──────────────────────────────────────────────────────────────────
  game({
    name: 'Catan: O Jogo (6ª edição)',
    brand: 'Devir',
    cents: 34900,
    ref: 9001,
    desc: 'Clássico moderno de negociação e construção: colonize a ilha de Catan, colete recursos e troque com os outros jogadores para erguer estradas, vilas e cidades.',
    specs: { players: '3-4', age: '10+', minutes: '60-120' },
    cols: ['catan', 'classicos-modernos', 'para-a-familia'],
    weight: 1500,
  }),
  game({
    name: 'Catan: Expansão 5-6 Jogadores (6ª edição)',
    brand: 'Devir',
    cents: 26900,
    ref: 9002,
    desc: 'Amplia Catan para 5 ou 6 jogadores, com peças e tabuleiro extras.',
    specs: { players: '5-6', age: '10+' },
    cols: ['catan'],
    weight: 900,
  }),
  game({
    name: 'Catan: O Jogo de Cartas (6ª edição)',
    brand: 'Devir',
    cents: 10400,
    ref: 9003,
    desc: 'Versão em cartas do clássico de colonização, para duelos rápidos entre 2 e 4 jogadores.',
    specs: { players: '2-4' },
    cols: ['catan', 'jogos-rapidos'],
    weight: 400,
  }),
  game({
    name: 'Carcassonne (3ª edição)',
    brand: 'Devir',
    cents: 29900,
    ref: 9004,
    desc: 'Monte a paisagem medieval peça a peça e posicione seguidores em estradas, cidades, mosteiros e campos para pontuar.',
    specs: { players: '2-5', age: '7+', minutes: '30-45' },
    cols: ['carcassonne', 'classicos-modernos', 'para-a-familia'],
    weight: 900,
  }),
  game({
    name: 'Carcassonne Big Box',
    brand: 'Devir',
    cents: 53900,
    ref: 9005,
    desc: 'Caixa de coleção que reúne o jogo base de Carcassonne e várias de suas expansões.',
    specs: { players: '2-6' },
    cols: ['carcassonne'],
    weight: 2200,
  }),
  game({
    name: 'Código Secreto (2ª edição)',
    brand: 'Devir',
    cents: 19400,
    ref: 9006,
    desc: 'Dois times de espiões: cada mestre dá uma dica de uma palavra para seus agentes encontrarem os codinomes certos sem acionar o assassino.',
    specs: { players: '2-8+', age: '14+', minutes: '15' },
    cols: ['party-games', 'jogos-rapidos', 'classicos-modernos'],
    weight: 600,
  }),
  game({
    name: 'Código Secreto: Dueto',
    brand: 'Devir',
    cents: 19400,
    ref: 9007,
    desc: 'Versão cooperativa de Código Secreto para duas pessoas: os dois dão dicas um ao outro para encontrar todos os agentes.',
    specs: { players: '2', minutes: '30' },
    cols: ['para-dois-jogadores', 'cooperativos'],
    weight: 500,
  }),
  game({
    name: 'Sushi Go',
    brand: 'Devir',
    cents: 9900,
    ref: 9008,
    desc: 'Jogo de cartas de escolher e passar: monte a melhor refeição de sushi ao longo de três rodadas.',
    specs: { players: '2-5', age: '8+', minutes: '15' },
    cols: ['jogos-rapidos', 'para-a-familia'],
    weight: 250,
  }),
  game({
    name: 'Sushi Go Party!',
    brand: 'Devir',
    cents: 15400,
    ref: 9009,
    desc: 'Versão ampliada de Sushi Go, com cardápios personalizáveis e até 8 jogadores.',
    specs: { players: '2-8', age: '8+', minutes: '20' },
    cols: ['jogos-rapidos', 'para-a-familia', 'party-games'],
    weight: 500,
  }),
  game({
    name: 'Twilight Struggle: A Guerra Fria',
    brand: 'Devir',
    cents: 47500,
    ref: 9010,
    desc: 'Duelo da Guerra Fria entre Estados Unidos e União Soviética: use cartas de eventos para disputar influência em todo o mundo.',
    specs: { players: '2', age: '13+', minutes: '120-180' },
    cols: ['estrategia', 'para-dois-jogadores', 'classicos-modernos'],
    weight: 1800,
  }),
  game({
    name: 'King of Tokyo Duel',
    brand: 'Devir',
    cents: 13900,
    ref: 9011,
    desc: 'Versão para dois jogadores do jogo de monstros gigantes rolando dados pela cidade.',
    specs: { players: '2' },
    cols: ['king-of-tokyo', 'para-dois-jogadores'],
    weight: 700,
  }),
  game({
    name: 'King of Tokyo: Monster Box',
    brand: 'Devir',
    cents: 41900,
    ref: 9012,
    desc: 'Edição de coleção de King of Tokyo, com o jogo e expansões numa só caixa.',
    specs: { players: '2-6' },
    cols: ['king-of-tokyo', 'para-a-familia'],
    weight: 2600,
  }),
  game({
    name: 'Exit: A Cabana Abandonada',
    brand: 'Devir',
    cents: 14400,
    ref: 9013,
    desc: 'Escape room de mesa: resolva enigmas com cartas, discos decodificadores e um livreto para escapar da cabana.',
    specs: { players: '1-4', age: '12+', minutes: '60-120' },
    cols: ['exit', 'cooperativos'],
    weight: 500,
  }),
  game({
    name: 'Exit: O Tesouro Afundado',
    brand: 'Devir',
    cents: 14400,
    ref: 9014,
    desc: 'Escape room de mesa: decifre pistas e enigmas para encontrar o tesouro afundado.',
    specs: { players: '1-4', age: '12+', minutes: '60-120' },
    cols: ['exit', 'cooperativos'],
    weight: 500,
  }),
  game({
    name: 'The White Castle',
    brand: 'Devir',
    cents: 25900,
    ref: 9015,
    desc: 'Estratégia no Japão feudal: use dados para posicionar seus personagens e construir o castelo de Himeji.',
    specs: { players: '1-4', minutes: '80' },
    cols: ['estrategia', 'novos-drops'],
    weight: 1300,
  }),
  game({
    name: 'Red Cathedral',
    brand: 'Devir',
    cents: 24900,
    ref: 9016,
    desc: 'Jogo de colocação de trabalhadores sobre a construção da Catedral de São Basílio, em Moscou.',
    specs: { players: '1-4', age: '10+', minutes: '80' },
    cols: ['estrategia'],
    weight: 1200,
  }),
  game({
    name: 'Through the Ages',
    brand: 'Devir',
    cents: 44900,
    ref: 9017,
    desc: 'Civilização em cartas: gerencie ciência, cultura, indústria e força militar do início dos tempos até a era moderna.',
    specs: { players: '2-4' },
    cols: ['estrategia', 'classicos-modernos'],
    weight: 1400,
  }),
  game({
    name: 'Mindbug: Primeiro Contato',
    brand: 'Devir',
    cents: 11900,
    ref: 9018,
    desc: 'Duelo de cartas de criaturas para 2 jogadores: cada um pode "mindbugar" uma criatura do rival e controlá-la.',
    specs: { players: '2', minutes: '20' },
    cols: ['para-dois-jogadores', 'jogos-rapidos', 'novos-drops'],
    weight: 300,
  }),
  game({
    name: 'Galaxy Trucker (1ª edição)',
    brand: 'Devir',
    cents: 15900,
    ref: 9019,
    desc: 'Monte sua nave contra o relógio com peças aleatórias e tente atravessar o espaço sem se desfazer no caminho.',
    specs: { players: '2-4' },
    cols: ['party-games'],
    weight: 1000,
  }),
  // ── Galápagos ──────────────────────────────────────────────────────────────
  game({
    name: 'Dixit',
    brand: 'Galápagos',
    cents: 28400,
    ref: 9020,
    desc: 'Jogo de contar histórias: dê uma dica para a sua carta ilustrada e tente ser adivinhado por alguns jogadores, mas não por todos.',
    specs: { players: '3-6', age: '8+', minutes: '30' },
    cols: ['para-a-familia', 'party-games', 'classicos-modernos'],
    weight: 1100,
  }),
  game({
    name: 'Dixit Odyssey',
    brand: 'Galápagos',
    cents: 34900,
    ref: 9021,
    desc: 'Versão de Dixit para até 12 jogadores, com 84 cartas ilustradas.',
    specs: { players: '3-12', age: '8+', minutes: '30' },
    cols: ['para-a-familia', 'party-games'],
    weight: 1300,
  }),
  game({
    name: 'Azul',
    brand: 'Galápagos',
    cents: 34900,
    ref: 9022,
    desc: 'Jogo de azulejos inspirado nos mosaicos portugueses: escolha peças coloridas para decorar as paredes do palácio real.',
    specs: { players: '2-4', age: '8+', minutes: '30-45' },
    cols: ['estrategia', 'para-a-familia', 'classicos-modernos'],
    weight: 1100,
  }),
  game({
    name: '7 Wonders: Duel',
    brand: 'Galápagos',
    cents: 24900,
    ref: 9023,
    desc: 'Versão para duas pessoas de 7 Wonders: construa maravilhas e vença por dominação militar, supremacia científica ou pontos.',
    specs: { players: '2', age: '10+', minutes: '30' },
    cols: ['para-dois-jogadores', 'estrategia', 'jogos-rapidos', 'classicos-modernos'],
    weight: 700,
  }),
  game({
    name: 'Ticket to Ride: Europa',
    brand: 'Galápagos',
    cents: 44900,
    ref: 9024,
    desc: 'Construa rotas de trem ligando as cidades da Europa. Esta edição traz túneis, balsas e estações.',
    specs: { players: '2-5', age: '8+', minutes: '30-60' },
    cols: ['para-a-familia', 'classicos-modernos'],
    weight: 1500,
  }),
  game({
    name: 'Kingdomino',
    brand: 'Galápagos',
    cents: 19900,
    ref: 9025,
    desc: 'Combine dominós de terrenos para montar seu reino 5x5 e pontuar por áreas e coroas.',
    specs: { players: '2-4', age: '8+', minutes: '15' },
    cols: ['para-a-familia', 'jogos-rapidos'],
    weight: 600,
  }),
  game({
    name: 'Patchwork',
    brand: 'Galápagos',
    cents: 19900,
    ref: 9026,
    desc: 'Duelo de colchas de retalhos para duas pessoas: compre peças com botões e preencha seu tabuleiro da melhor forma.',
    specs: { players: '2', age: '8+', minutes: '15-30' },
    cols: ['para-dois-jogadores', 'jogos-rapidos'],
    weight: 700,
  }),
  game({
    name: 'Magic Maze',
    brand: 'Galápagos',
    cents: 27900,
    ref: 9027,
    desc: 'Cooperativo em tempo real: todos movem qualquer herói, mas cada jogador só pode fazer um tipo de ação. E ninguém pode falar!',
    specs: { players: '1-8', age: '8+', minutes: '15' },
    cols: ['cooperativos', 'jogos-rapidos', 'party-games'],
    weight: 800,
  }),
  game({
    name: 'Takenoko',
    brand: 'Galápagos',
    cents: 39900,
    ref: 9028,
    desc: 'Cuide do bambuzal do imperador do Japão e do seu panda: plante, regue e alimente para cumprir objetivos.',
    specs: { players: '2-4', age: '8+', minutes: '45' },
    cols: ['para-a-familia'],
    weight: 1500,
  }),
  game({
    name: 'Scythe',
    brand: 'Galápagos',
    cents: 69900,
    ref: 9029,
    desc: 'Estratégia numa Europa alternativa dos anos 1920, com mechs, facções assimétricas e controle de território.',
    specs: { players: '1-5', age: '14+', minutes: '90-115' },
    cols: ['estrategia', 'classicos-modernos'],
    weight: 4200,
  }),
  // ── Grok Games ─────────────────────────────────────────────────────────────
  game({
    name: 'Wingspan',
    brand: 'Grok Games',
    cents: 44900,
    ref: 9030,
    desc: 'Construção de motores sobre aves: atraia pássaros para os seus habitats e ative as habilidades de cada um.',
    specs: { players: '1-5', age: '10+', minutes: '40-70' },
    cols: ['estrategia', 'classicos-modernos', 'para-a-familia'],
    weight: 1600,
  }),
  // ── MeepleBR ───────────────────────────────────────────────────────────────
  game({
    name: 'Terraforming Mars',
    brand: 'MeepleBR',
    cents: 34990,
    ref: 9031,
    desc: 'Corporações competem para transformar Marte em um planeta habitável, elevando temperatura, oxigênio e oceanos.',
    specs: { players: '1-5', age: '12+', minutes: '120' },
    cols: ['terraforming-mars', 'estrategia', 'classicos-modernos'],
    weight: 3300,
  }),
  game({
    name: 'Terraforming Mars: Prelúdio',
    brand: 'MeepleBR',
    cents: 14900,
    ref: 9032,
    desc: 'Expansão que acrescenta uma fase inicial de cartas para acelerar o começo da partida.',
    cols: ['terraforming-mars'],
    weight: 300,
  }),
  game({
    name: 'Terraforming Mars: Hellas e Elysium',
    brand: 'MeepleBR',
    cents: 11900,
    ref: 9033,
    desc: 'Expansão com dois novos mapas do planeta.',
    cols: ['terraforming-mars'],
    weight: 400,
  }),
  game({
    name: 'Terraforming Mars: Colônias',
    brand: 'MeepleBR',
    cents: 17900,
    ref: 9034,
    desc: 'Expansão que leva colônias às luas e planetas do sistema solar.',
    cols: ['terraforming-mars'],
    weight: 700,
  }),
  game({
    name: 'Terraforming Mars: Reviravolta',
    brand: 'MeepleBR',
    cents: 17900,
    ref: 9035,
    desc: 'Expansão de política, com a Assembleia Global de Marte, delegados e eventos.',
    cols: ['terraforming-mars'],
    weight: 700,
  }),
  game({
    name: 'Terraforming Mars: O Jogo de Dados',
    brand: 'MeepleBR',
    cents: 24990,
    ref: 9036,
    desc: 'Versão rápida em dados do jogo de terraformação de Marte.',
    cols: ['terraforming-mars', 'jogos-rapidos'],
    weight: 900,
  }),
  game({
    name: 'Root',
    brand: 'MeepleBR',
    cents: 48990,
    ref: 9037,
    desc: 'Guerra assimétrica na floresta: cada facção joga de um jeito diferente e disputa o controle do território.',
    specs: { players: '2-4', age: '10+', minutes: '60-90' },
    cols: ['root', 'estrategia', 'classicos-modernos'],
    weight: 2200,
  }),
  game({
    name: 'Root: Pacote do Malandro',
    brand: 'MeepleBR',
    cents: 7900,
    ref: 9038,
    desc: 'Pacote de expansão para Root.',
    cols: ['root'],
    weight: 200,
  }),
  game({
    name: 'Root: Autômata 2',
    brand: 'MeepleBR',
    cents: 21900,
    ref: 9039,
    desc: 'Expansão que permite jogar Root com facções controladas por regras automáticas, para partidas solo ou com poucos jogadores.',
    cols: ['root'],
    weight: 500,
  }),
  game({
    name: 'Arcs: Conflito e Colapso no Vértice',
    brand: 'MeepleBR',
    cents: 44900,
    ref: 9040,
    desc: 'Estratégia espacial de Cole Wehrle: dispute influência, recursos e ordem em uma galáxia em colapso.',
    specs: { players: '2-4', age: '14+', minutes: '60-120' },
    cols: ['estrategia', 'novos-drops'],
    weight: 2000,
  }),
  game({
    name: 'Piratas de Maracaibo',
    brand: 'MeepleBR',
    cents: 37900,
    ref: 9041,
    desc: 'Jogo de piratas no Caribe do século XVII: navegue, comercie, lute e ganhe fama.',
    specs: { players: '1-4' },
    cols: ['estrategia', 'novos-drops'],
    weight: 1600,
  }),
  game({
    name: 'Imperium: Classics',
    brand: 'MeepleBR',
    cents: 25900,
    ref: 9042,
    desc: 'Jogo de construção de civilizações em cartas: erga um império e administre seu declínio.',
    cols: ['imperium', 'estrategia'],
    weight: 700,
  }),
  game({
    name: 'Imperium: Legends',
    brand: 'MeepleBR',
    cents: 25900,
    ref: 9043,
    desc: 'Segunda caixa independente de Imperium, com novas civilizações.',
    cols: ['imperium', 'estrategia'],
    weight: 700,
  }),
  game({
    name: 'Eclipse: O Segundo Despertar da Galáxia',
    brand: 'MeepleBR',
    cents: 129900,
    ref: 9044,
    desc: 'Império galáctico 4X: explore, expanda, pesquise e conquiste em partidas épicas com raças alienígenas.',
    specs: { players: '2-6', age: '14+', minutes: '60-200' },
    cols: ['estrategia'],
    weight: 5200,
  }),
  game({
    name: 'Unmatched Aventuras: Contos Fantásticos',
    brand: 'MeepleBR',
    cents: 54900,
    ref: 9045,
    desc: 'Duelos táticos entre heróis e lendas, com decks e tabuleiros próprios.',
    cols: ['para-dois-jogadores'],
    status: 'draft',
    weight: 1800,
  }),
];
